project:
  type: website

website:
  title: "Dane Brink"
  navbar:
    logo: images/University-of-Michigan.jpg
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
    smooth-scroll: true
    link-external-newwindow: true
