project:
  type: website

website:
  title: "Dane Brink"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Contact
        href: contact.qmd

format:
  html:
    theme: cosmo
    toc: false
    page-layout: full
    smooth-scroll: true
    link-external-newwindow: true
